### ISSUE TITLE
@types/photoshop not found when npm install

### ISSUE THREAD

**Issue by bit-pete** [jardicc/alchemist#12]
when npm install it show this error
"fatal: repository 'https://github.com/adobe-uxp/types-photoshop.git/' not found"
Is this path still exist or use other path

**Comment by jardicc** [comment]
duplicate of: https://github.com/jardicc/alchemist/issues/7

**Comment by jardicc** [comment]
I am implementing official UXP-PS types https://twitter.com/J_Bereza/status/1458910672629157897
