### ISSUE TITLE
.atn conversion

### ISSUE THREAD

**Issue by jstvnsn** [jardicc/alchemist#23]
Is there any instruction set covering "e.g. record action file (.atn) -> Read it as JSON via Occultist -> Pass it into Alchemist to generate source code -> Generate plugin from generated source code"?

if anyone wants to help me make such a tutorial, then please shout out. 

p.s. there is a placeholder now for this sitting in the Adobe UXP Developer Tool

**Comment by jardicc** [comment]
Not full coverage. But if you watch one video after another then it should help a lot :-)

**Comment by jardicc** [comment]
Photoshop has now JS conversion by default. 
Actions -> flyout menu -> Copy as Javascript

Make sure that action is selected.
