### ISSUE TITLE
Dev Setup confusion. Where am I supossed to run the node npm commands?

### ISSUE THREAD

**Issue by visusys** [jardicc/alchemist#29]
See image:

![firefox_UpebmGnYSh](https://user-images.githubusercontent.com/33441569/180677779-eb965a3a-cc88-40e9-9dba-9c8020dbaff1.png)

Do I need to run `npm install` and `npm build` to get alchemist working properly, or are those commands only if you have an existing panel that you want to see?

Some clarification would be helpful.

**Comment by jardicc** [comment]
Dev setup = if you want to rewrite its source code and change its functionality. 

Otherwise download source code in zip archive and follow this only: https://github.com/jardicc/alchemist#quick-usage---development-version-recommended
