### ISSUE TITLE
Action Replays defaults Image depth to 12-bit on application startup

### ISSUE THREAD

**Issue by OfficerArtoria** [jardicc/alchemist#34]
I have saved an action that ends with a file save to AVIF with Image depth set to 8bit. The action itself works well in most circumstances, except whenever I start my Photoshop up, it defaults to 12-bit. This requires re-recording the action again, which would be default back to 8-bit. Other parameters are working for me properly for Action Replay.

**Comment by gregbenz** [comment]
Are you referring to working with the 3rd-party AVIF plugin? PS does not natively support AVIF (ACR does, but not in a way that supports actions/script).

**Comment by jardicc** [comment]
If this is 3rd party plugin then there is nothing I can do... because it is the responsibility of the plugin developer to implement action recording correctly.

**Comment by OfficerArtoria** [comment]
Sorry about it, I am new to this platform and posted in the wrong repository, thank you for pointing out.
