### ISSUE TITLE
Cannot increase limit in alchemist settings.

### ISSUE THREAD

**Issue by karpiyon** [jardicc/alchemist#40]
Hi,
I am trying to modify an existing action and read it into alchemist.
After reading it to Occultlist I am trying to "Replace in Alchemist"
I got an error that alchemist can only show 150 items.
I changed: `"maximumItems": 1500`, in both:
c:\Users\chupi\AppData\Roaming\Adobe\UXP\PluginsStorage\PHSP\**23**\Developer\2bcdb900\PluginData\
&
c:\Users\chupi\AppData\Roaming\Adobe\UXP\PluginsStorage\PHSP\**24**\Developer\2bcdb900\PluginData\

Restarted PS, reloaded alchemist and I get the same error.
I am running PS beta and I am loading alchemist using the UXP developer tool.

Where should I change those settings?

Thanks

**Comment by karpiyon** [comment]
Found it under PHSPBETA...

**Comment by jardicc** [comment]
Hello, you could find it in settings 
![image](https://github.com/jardicc/alchemist/assets/13526959/9c5d534e-5c2a-4d6d-8178-c172b2e84ae8)

**Comment by jardicc** [comment]
Please note: when you do change in Alchemist do not touch anything for 10 seconds and settings will be saved. 
https://github.com/jardicc/alchemist/blob/4d971ce2aa9ce851cc115a082b110227cff3f322/src/inspector/classes/Settings.ts#L38

**Comment by karpiyon** [comment]
Thanks.
I did not see the "Settings" button...
BTW, **thanks for the great job you did and for sharing it**.
Without it it would have not been possible to migrate CEP plugins , not create new complex ones.

**Comment by karpiyon** [comment]
Do you have any ideas as how to debug an action which is not working once turned to a Batch Play function?
I have an old action which I am trying to 'fix'.
While I can use Occultlist  to generate batch ply functions for small action, which work, I was not able to get the same result with the large action which does not work.
Not working means that photoshop ended the action in the meddle complain something about a "command select is not currently available". 
When I try to run it, after turning to batch play I get:
![image](https://github.com/jardicc/alchemist/assets/29725225/38b04d06-1187-4e79-af5e-756a91b56c18)

How can I know what causes this within the batch play function?

Thanks

**Comment by jardicc** [comment]
Would `continueOnError` fix that? https://developer.adobe.com/photoshop/uxp/2022/ps_reference/media/batchplay/#continueonerror-default-false

Please note that this one is a recent addition and works only in the latest PS versions.

**Comment by karpiyon** [comment]
I'll give it a try.
Do you know how/where to set this option?
