### ISSUE TITLE
Please make sure to use dist folder and NOT uxp folder.

### ISSUE THREAD

**Issue by jmverges** [jardicc/alchemist#46]
If I use manisfest inside dist folder it fails due invalid json. Howver if I use uxp folder it loads in UXP but when going to PS I just see a window saying: "are you sure you want to use uxp instead of dist folder?" but I cannot accept or refuse, just close the dialog

**Comment by arrowtype** [comment]
Same issue here. The manifest.json file in the dist folder seems like invalid JSON.

<img width="953" alt="image" src="https://github.com/jardicc/alchemist/assets/45946693/24485a71-6bc5-4186-85f7-b9db74217c9d">

**Comment by arrowtype** [comment]
Ahh, I think I found the solution:

Download the source from the releases https://github.com/jardicc/alchemist/releases/tag/2.7.0

_...not_ from the zip download on the front page of the repo.

In the releases download, dist/manifest.json is actual JSON, and loading it in UXP seems to actually launch the expected plugin in Photoshop.

**Comment by jardicc** [comment]
I wanted to make repo more performant using LFS... but people are installing repo link files instead plugin itself... so I will probably change it back.

**Comment by jardicc** [comment]
https://docs.github.com/en/repositories/working-with-files/managing-large-files

**Comment by jardicc** [comment]
So I changed setting in this repo and hopefully it should work now same as before.

![image](https://github.com/jardicc/alchemist/assets/13526959/a96dcc49-3d51-419c-8275-433ec25e02be)
