### ISSUE TITLE
Fonts Are To Small

### ISSUE THREAD

**Issue by Ian-Barber** [jardicc/alchemist#5]
**MAC OSX 10.15.17
Photoshop CC 2021**

I am finding that the font size is to small and hard to read, can they be increased ?

![Screenshot 2020-10-27 at 12 10 50](https://user-images.githubusercontent.com/50799487/97299843-83efa080-184d-11eb-8282-ccc7a77407dd.jpg)

**Comment by jardicc** [comment]
Will be improved in 1.2.0
