### ISSUE TITLE
UXP code from Photoshop Actions

### ISSUE THREAD

**Issue by jstvnsn** [jardicc/alchemist#6]
I would like to be able to use Alchemist in the follwing workflow: pre-recorded single Action > ActionToJavascript (specifically, the xbytor xtools utility) > Action Manager Code polyfill for UXP. Two sample scripts - generated with xtools - are provided here for test purposes.

[resources_jls_071120.zip](https://github.com/jardicc/alchemist/files/5504808/resources_jls_071120.zip)

**Comment by jardicc** [comment]
I am considering it. This would require quite some time since I have to write a binary parser from scratch and `.fromStream()` function is not yet present in UXP.

**Comment by jstvnsn** [comment]
Thanks. Does that missing functionality appear in the development roadmap just updated for UXP by Adobe: https://trello.com/b/Qag1BazI/q4-roadmap? If not, can I help with that?

**Comment by jardicc** [comment]
It doesn't. I can do that feature myself. It will just take longer because this means that I have to write a binary parser not only for actions hierarchy but also descriptors itself with all their data types. So it is just more work.

**Comment by jardicc** [comment]
Implemented in version 1.5.0

**Comment by jstvnsn** [comment]
Thanks for your efforts. I have not a totally bored Occultist. The basic functionality seems OK, But I see that there are transfer errors, from Occultist back to Alchemist. Can I send the details by email?
