### ISSUE TITLE
Issues with dev setup

### ISSUE THREAD

**Issue by gkaizer** [jardicc/alchemist#7]
Node ver 15.0.1
Npm 7.0.3
win10

After cloning repository and launching npm install in console I have some errors:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@0.2.0
npm ERR! Found: typescript@4.0.5
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^2.7 || ^3" from awesome-typescript-loader@5.2.1
npm ERR! node_modules/awesome-typescript-loader
npm ERR!   awesome-typescript-loader@"^5.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

it seems like it is not able to resolve for typescript 2.7 or 3
I tried also npm install --legacy-peer-deps, but it stopped after a while with this error
.........
3756 error code 128
3757 error command failed
3758 error command git ls-remote ssh://git@github.com/adobe-uxp/types-photoshop.git
3759 error Host key verification failed.
3759 error fatal: Could not read from remote repository.
3759 error
3759 error Please make sure you have the correct access rights
3759 error and the repository exists.

it seems like I am not able to access github.com/adobe-uxp/types-photoshop.git

any ideas?

**Comment by jardicc** [comment]
It seems that Awesome Typescript Loader wants version ^2.7 or ^3 https://github.com/s-panferov/awesome-typescript-loader/blob/master/package.json#L46 
Anyway, my project uses 4.0.3 and that is not gonna be downgraded. 

I do use node version 12.16.1 and npm version 6.13.4 Maybe it handled differently there.

And as you mentioned one of the modules (UXP API type definitions) are located in a private Adobe repository) I already asked them to move it to the public repo. Once they do it I will change dependency.

**Comment by jardicc** [comment]
I am implementing official UXP-PS types https://twitter.com/J_Bereza/status/1458910672629157897
